#lvm 磁盘分区
- hosts: add-servers
  user: root
  gather_facts: True
  vars: 
    mntp: "/app /ini /data /log"
  tasks:
  - name: filesystem | Create pv,vg,lv and file systems
    lvg:  vg=VolGroup1  pvs=/dev/sdb

  - name: filesystem | create lv_app
    lvol: vg=VolGroup1  lv=lv_app  size=10G
  - name: filesystem | create lv_data
    lvol: vg=VolGroup1  lv=lv_data  size=10G
  - name: filesystem | create lv_ini
    lvol: vg=VolGroup1  lv=lv_ini  size=1G
  - name: filesystem | create lv_log
    lvol: vg=VolGroup1  lv=lv_log  size=100%FREE

  - name: filesystem | create fs
    filesystem: fstype=ext4 dev=/dev/VolGroup1/{{ item }}
    with_items:
      - lv_app
      - lv_data
      - lv_ini
      - lv_log

  - name: Creates directory
    file: path=${mntp} state=directory

  - name: filesytem | mount dir
    mount: name=/{{item}} src=/dev/VolGroup1/lv_{{item}} dump=1 passno=1 fstype=ext4 state=mounted
    with_items:
      - app
      - data
      - ini
      - log
