# Using alternate directory locations:
- hosts: add-servers
  user: root
  tasks:
   - name: ssh-copy
     authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
     tags:
       - sshkey
